import 'package:flutter/material.dart';
import 'project.dart';
import 'resource.dart';

class MockData {
  static final List<ResourceItem> sampleResources = [
    const ResourceItem(
      id: 'res-1',
      title: 'UI Architecture Guidelines',
      content: 'Feature-first clean architecture pattern with modular presentation layers.',
      type: ResourceType.note,
      category: 'Engineering',
      createdAt: 'Today, 10:30 AM',
      tags: ['Flutter', 'Architecture', 'BestPractices'],
      isFavorite: true,
    ),
    const ResourceItem(
      id: 'res-2',
      title: 'Figma Design System',
      content: 'Complete component library, color tokens, and layout guidelines for Organizer.',
      type: ResourceType.link,
      category: 'Design',
      createdAt: 'Yesterday',
      url: 'https://figma.com/@organizer-app',
      tags: ['Figma', 'UI/UX', 'Components'],
      isFavorite: true,
    ),
    const ResourceItem(
      id: 'res-3',
      title: 'Dark Theme Background',
      content: '#0A0B12 - Deep cosmic background color token for night mode.',
      type: ResourceType.color,
      category: 'Design',
      createdAt: '2 days ago',
      colorHex: '#0A0B12',
      tags: ['Theme', 'ColorToken', 'Dark'],
    ),
    const ResourceItem(
      id: 'res-4',
      title: 'Primary Purple Token',
      content: '#8B5CF6 - Vibrant brand accent purple used across interactive elements.',
      type: ResourceType.color,
      category: 'Design',
      createdAt: '2 days ago',
      colorHex: '#8B5CF6',
      tags: ['Accent', 'Brand', 'ColorToken'],
      isFavorite: true,
    ),
    const ResourceItem(
      id: 'res-5',
      title: 'Inter Font Specification',
      content: 'Primary body and headline font family configured in Google Fonts.',
      type: ResourceType.typography,
      category: 'Typography',
      createdAt: '3 days ago',
      fontFamily: 'Inter',
      tags: ['Font', 'Typography', 'GoogleFonts'],
    ),
    const ResourceItem(
      id: 'res-6',
      title: 'User Flow Diagram PDF',
      content: 'Complete user onboarding and navigation wireframe specification.',
      type: ResourceType.pdf,
      category: 'Documentation',
      createdAt: '4 days ago',
      url: 'https://docs.organizer.app/flow.pdf',
      tags: ['PDF', 'Wireframes', 'Specs'],
    ),
    const ResourceItem(
      id: 'res-7',
      title: 'Hero Banner Mockup',
      content: 'High-resolution glassmorphism mockup for app store listing.',
      type: ResourceType.image,
      category: 'Assets',
      createdAt: '5 days ago',
      tags: ['Mockup', 'Banner', 'Assets'],
    ),
    const ResourceItem(
      id: 'res-8',
      title: 'GitHub Repository',
      content: 'Official Flutter codebase repository for Organizer workspace tool.',
      type: ResourceType.link,
      category: 'Engineering',
      createdAt: '1 week ago',
      url: 'https://github.com/organizer/flutter-app',
      tags: ['Git', 'SourceCode', 'Flutter'],
    ),
  ];

  static final List<ProjectItem> sampleProjects = [
    ProjectItem(
      id: 'proj-1',
      title: 'Organizer App',
      description: 'Next-gen workspace app built with Flutter and dark glassmorphism aesthetics.',
      category: 'Mobile App',
      itemsCount: 24,
      updated: '2h ago',
      color: const Color(0xFF8B5CF6),
      isFavorite: true,
      resources: sampleResources.sublist(0, 4),
    ),
    ProjectItem(
      id: 'proj-2',
      title: 'Portfolio 2026',
      description: 'Interactive web portfolio showcasing creative design systems and mobile apps.',
      category: 'Web Design',
      itemsCount: 12,
      updated: 'Yesterday',
      color: const Color(0xFF38BDF8),
      isFavorite: true,
      resources: sampleResources.sublist(2, 6),
    ),
    ProjectItem(
      id: 'proj-3',
      title: 'Design System',
      description: 'Comprehensive token library with dark colors, typography specs, and icons.',
      category: 'Design System',
      itemsCount: 43,
      updated: '3 days ago',
      color: const Color(0xFF34D399),
      isFavorite: false,
      resources: sampleResources.sublist(1, 5),
    ),
    ProjectItem(
      id: 'proj-4',
      title: 'AI Assistant Specs',
      description: 'Prompts, persona guidelines, and API integration documentation.',
      category: 'AI Tools',
      itemsCount: 8,
      updated: '5 days ago',
      color: const Color(0xFFF97316),
      isFavorite: false,
      resources: sampleResources.sublist(0, 3),
    ),
    ProjectItem(
      id: 'proj-5',
      title: 'Brand Identity',
      description: 'Logos, brand guidelines, typography palettes, and presentation decks.',
      category: 'Branding',
      itemsCount: 18,
      updated: '1 week ago',
      color: const Color(0xFFEC4899),
      isFavorite: true,
      resources: sampleResources.sublist(3, 7),
    ),
  ];
}
